FROM maven:3.8-jdk-11 AS builder

WORKDIR /app

COPY pom.xml ./
RUN mvn clean install

FROM openjdk:11-slim

WORKDIR /app

COPY build/libs/restaurant-service-2.7.7.jar app.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "app.jar"]
