version: "3.8"  # Adjust version if needed based on your Docker environment

services:
  user-service:
    build: ./user-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  restaurant-service:
    build: ./restaurant-service
    ports:
      - "8081:8081"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
    networks:
      - shared-net
    volumes:
      - /postgres/data 

